apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: fa3bian-order
    meta.helm.sh/release-namespace: fan3bian
  creationTimestamp: "2020-12-31T09:00:34Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: fa3bian-order-dp
  namespace: fan3bian
  resourceVersion: "9526543"
  selfLink: /apis/apps/v1/namespaces/fan3bian/deployments/fa3bian-order-dp
  uid: 9a03c4ee-89a2-41d6-8934-7fc03a2261b1
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fa3bian-order
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fa3bian-order
    spec:
      containers:
      - image: dockerregistry.fan3bian.com/fan3bian/fa3bian-order:v20201231_164755
        imagePullPolicy: IfNotPresent
        name: fa3bian-order
        ports:
        - containerPort: 10996
          name: dubbo
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 4200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/application.properties
          name: fa3bian-order-cm
          subPath: application.properties
        - mountPath: /usr/tmp/important.properties
          name: fa3bian-order-cm
          subPath: important.properties
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/prop/jdbc.properties
          name: fa3bian-order-cm
          subPath: jmq.properties
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/prop/mq/kafka.properties
          name: fa3bian-order-cm
          subPath: kafka.properties
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/log4j2.xml
          name: fa3bian-order-cm
          subPath: log4j2.xml
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/prop/cache/redis.properties
          name: fa3bian-order-cm
          subPath: rpc.properties
        - mountPath: /usr/fa3bian-order/fa3bian-order-main/conf/spring/spring-main.xml
          name: fa3bian-order-cm
          subPath: spring-main.xml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: fa3bian-order-cm
        name: fa3bian-order-cm
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-12-31T09:00:34Z"
    lastUpdateTime: "2020-12-31T09:00:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-12-31T09:00:34Z"
    lastUpdateTime: "2020-12-31T09:00:57Z"
    message: ReplicaSet "fa3bian-order-dp-7b65c7f444" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
